"use client";
import Link from "next/link";
import { useState } from "react";
import { CheckCircle2, Loader2, ShieldCheck, UsersRound } from "lucide-react";

export function ProfileForm({ initial }: { initial: { email: string; nickname: string; mobile: string } }) {
  const [nickname,setNickname]=useState(initial.nickname); const [mobile,setMobile]=useState(initial.mobile); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [ok,setOk]=useState(false);
  async function save(){setLoading(true);setError("");setOk(false);const response=await fetch("/api/profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({nickname,mobile})});const json=await response.json().catch(()=>({}));setLoading(false);if(!response.ok){setError(json.error||"保存失败");return;}setOk(true);}
  return <section className="px-5 py-6"><div className="rounded-[20px] bg-[#eef7ff] p-4 text-[11px] leading-5 text-[#53677e]"><ShieldCheck size={17} className="mr-2 inline text-[var(--app-blue)]"/>联系方式仅用于需求确认、订单沟通和必要服务通知。</div><div className="mt-5 space-y-4"><label className="block"><span className="mb-2 block text-[12px] font-semibold">登录邮箱</span><div className="flex h-12 items-center rounded-[15px] border border-[#e3eaf2] bg-[#f5f7fa] px-4 text-[13px] text-[#7c8999]">{initial.email}</div></label><label className="block"><span className="mb-2 block text-[12px] font-semibold">昵称</span><input value={nickname} onChange={e=>setNickname(e.target.value)} maxLength={20} placeholder="怎么称呼你" className="h-12 w-full rounded-[15px] border border-[#dce8f4] bg-white px-4 text-[13px] outline-none focus:border-[#1677ff]"/></label><label className="block"><span className="mb-2 block text-[12px] font-semibold">手机号 / 联系方式</span><input value={mobile} onChange={e=>setMobile(e.target.value)} maxLength={20} placeholder="用于订单沟通" className="h-12 w-full rounded-[15px] border border-[#dce8f4] bg-white px-4 text-[13px] outline-none focus:border-[#1677ff]"/></label>{error?<p className="rounded-[14px] bg-red-50 px-4 py-3 text-[11px] text-red-700">{error}</p>:null}{ok?<p className="flex items-center gap-2 rounded-[14px] bg-emerald-50 px-4 py-3 text-[11px] text-emerald-700"><CheckCircle2 size={15}/>账号资料已保存</p>:null}<button type="button" onClick={save} disabled={loading} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-[17px] bg-[var(--app-blue)] text-[13px] font-semibold text-white">{loading?<><Loader2 size={16} className="animate-spin"/>保存中…</>:"保存资料"}</button><Link href="/travelers" className="flex min-h-14 items-center gap-3 rounded-[18px] border border-[#dce8f4] bg-white px-4"><UsersRound size={18} className="text-[var(--app-blue)]"/><div><p className="text-[12px] font-semibold">管理常用旅客</p><p className="mt-1 text-[10px] text-[var(--app-muted)]">同行人姓名与证件信息</p></div></Link></div></section>;
}
