import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, MapPin, Sparkles } from "lucide-react";
import { AppBottomNav } from "@/components/AppBottomNav";

export function PlatformFrame({ title, subtitle, back = "/", children, active = "discover" }: { title: string; subtitle?: string; back?: string; children: React.ReactNode; active?: string }) {
  return <div className="min-h-screen bg-[#eaf2fb] text-[var(--app-ink)]"><main className="mx-auto min-h-screen w-full max-w-[520px] bg-[var(--app-bg)] pb-[calc(96px+env(safe-area-inset-bottom))]"><header className="sticky top-0 z-30 flex items-center gap-3 border-b border-white/70 bg-white/85 px-5 pb-3 pt-[max(12px,env(safe-area-inset-top))] backdrop-blur-2xl"><Link href={back} className="grid size-10 place-items-center rounded-[14px] border border-[#dce8f4] bg-white" aria-label="返回"><ArrowLeft size={19}/></Link><div className="min-w-0 flex-1"><h1 className="truncate text-[19px] font-semibold">{title}</h1>{subtitle&&<p className="mt-0.5 truncate text-[10px] text-[var(--app-muted)]">{subtitle}</p>}</div><Link href="/ai" className="grid size-10 place-items-center rounded-[14px] bg-[var(--app-blue-soft)] text-[var(--app-blue)]" aria-label="AI规划"><Sparkles size={18}/></Link></header>{children}</main><AppBottomNav active={active} compact/></div>
}

export function EmptyState({ title, note, href = "/explore", action = "去发现" }: { title: string; note: string; href?: string; action?: string }) { return <div className="app-card mx-5 mt-6 px-6 py-12 text-center"><div className="mx-auto grid size-14 place-items-center rounded-full bg-[var(--app-blue-soft)] text-[var(--app-blue)]"><MapPin size={24}/></div><h2 className="mt-4 text-[17px] font-semibold">{title}</h2><p className="mt-2 text-[12px] leading-5 text-[var(--app-muted)]">{note}</p><Link href={href} className="mt-5 inline-flex min-h-11 items-center rounded-full bg-[var(--app-blue)] px-5 text-[12px] font-semibold text-white">{action}</Link></div> }

export function Price({ value, state = "REFERENCE" }: { value?: number; state?: string }) { const label = state === "CONFIRMED" ? "最终确认价" : state === "ESTIMATED" ? "预估价 / 人起" : value ? "参考价 / 人起 · 待确认" : "待确认"; return <div className="text-right"><p className="text-[18px] font-semibold text-[var(--app-blue-deep)]">{value ? `¥${value.toLocaleString()}` : "待确认"}</p><p className="text-[10px] text-[var(--app-muted)]">{label}</p></div> }

export function CatalogHero({ eyebrow, title, note }: { eyebrow: string; title: string; note: string }) { return <section className="mx-5 mt-5 rounded-[24px] bg-[#0d315d] px-5 py-6 text-white shadow-[0_16px_34px_rgba(7,45,91,.18)]"><p className="text-[10px] font-semibold tracking-[.18em] text-[#9ed0ff]">{eyebrow}</p><h2 className="mt-2 text-[25px] font-semibold">{title}</h2><p className="mt-2 text-[12px] leading-5 text-white/70">{note}</p></section> }

export function FilterChips({ items, active = "全部" }: { items: string[]; active?: string }) { return <div className="no-scrollbar mt-4 flex gap-2 overflow-x-auto px-5 pb-1">{items.map((item)=><Link key={item} href={item === "全部" ? "?" : `?filter=${encodeURIComponent(item)}`} className={`inline-flex min-h-10 shrink-0 items-center rounded-full px-4 text-[12px] font-semibold ${active===item?"bg-[var(--app-blue)] text-white":"border border-[#dce8f4] bg-white text-[#53677e]"}`}>{item}</Link>)}</div> }

export function TourCard({ tour }: { tour: { slug:string; name:string; destination:string; departure:string; days:number; type:string; tags:string[]; image:string; price:number; priceState:string; summary:string } }) { return <Link href={`/tours/${tour.slug}`} className="app-card app-press block overflow-hidden"><div className="relative h-[178px]"><img src={tour.image} alt={tour.name} className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#071d3d]/75 to-transparent"/><span className="absolute left-3 top-3 rounded-full bg-white/90 px-3 py-1 text-[10px] font-semibold text-[#0d315d]">{tour.type}</span><div className="absolute bottom-3 left-4 right-4 text-white"><p className="text-[10px] text-white/72">{tour.destination} · {tour.days}天 · {tour.departure}出发</p><h3 className="mt-1 text-[18px] font-semibold">{tour.name}</h3></div></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[12px] leading-5 text-[var(--app-muted)]">{tour.summary}</p><div className="mt-3 flex flex-wrap gap-1.5">{tour.tags.map((t)=><span key={t} className="rounded-full bg-[var(--app-blue-soft)] px-2.5 py-1 text-[10px] font-medium text-[var(--app-blue-deep)]">{t}</span>)}</div></div><Price value={tour.price} state={tour.priceState}/></div><div className="mt-4 flex items-center justify-between text-[11px] font-semibold text-[var(--app-blue)]"><span>查看详情与班期</span><ArrowRight size={15}/></div></div></Link> }

export function ActivityCard({ item }: { item: {slug:string; name:string; location:string; category:string; image:string; price:number; summary:string} }) { return <Link href={`/activities/${item.slug}`} className="app-card app-press flex gap-3 overflow-hidden p-3"><img src={item.image} alt={item.name} className="size-[104px] shrink-0 rounded-[17px] object-cover"/><div className="min-w-0 flex-1"><span className="text-[10px] font-semibold text-[var(--app-blue)]">{item.category}</span><h3 className="mt-1 truncate text-[15px] font-semibold">{item.name}</h3><p className="mt-1 text-[10px] text-[var(--app-muted)]">{item.location}</p><p className="mt-2 line-clamp-2 text-[11px] leading-4 text-[#53677e]">{item.summary}</p><p className="mt-2 text-[11px] font-medium text-[var(--app-blue-deep)]">提交日期与人数，获取当日报价 →</p></div></Link> }

export function PackageCard({ item }: { item: {slug:string; name:string; hotel:string; benefits:string[]; image:string; price:number} }) { return <Link href={`/packages/${item.slug}`} className="app-card app-press overflow-hidden"><img src={item.image} alt={item.name} className="h-[150px] w-full object-cover"/><div className="p-4"><h3 className="text-[16px] font-semibold">{item.name}</h3><p className="mt-1 text-[11px] text-[var(--app-muted)]">{item.hotel}</p><div className="mt-3 flex flex-wrap gap-1.5">{item.benefits.map((b)=><span key={b} className="rounded-full bg-[#eef7ff] px-2.5 py-1 text-[10px] text-[var(--app-blue-deep)]">{b}</span>)}</div><div className="mt-4 flex items-center justify-between"><span className="text-[11px] text-[var(--app-muted)]">费用按日期与人数确认</span><span className="text-[11px] font-semibold text-[var(--app-blue)]">提交套餐询价 →</span></div></div></Link> }

export function StatusBadge({ children }: { children: React.ReactNode }) { return <span className="inline-flex items-center gap-1 rounded-full bg-[#eaf9f0] px-3 py-1.5 text-[10px] font-semibold text-[#19884b]"><CheckCircle2 size={12}/>{children}</span> }
