import Link from "next/link";
import { ArrowRight, ClipboardList, Plus } from "lucide-react";
import { PlatformFrame } from "@/components/platform/Catalog";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/userAuth";

const labels:Record<string,string>={SUBMITTED:"已提交",IN_REVIEW:"审核中",INQUIRING:"顾问确认中",WAITING_FINAL_QUOTE:"待最终报价",FINAL_QUOTED:"已报价",USER_CONFIRMED:"已确认",WAITING_PAYMENT:"待付款",PAID:"已付款",FULFILLING:"履约中",BOOKED:"已预订",COMPLETED:"已完成",CANCELLED:"已取消"};
const tones:Record<string,string>={SUBMITTED:"bg-blue-50 text-blue-700",IN_REVIEW:"bg-amber-50 text-amber-700",INQUIRING:"bg-amber-50 text-amber-700",WAITING_FINAL_QUOTE:"bg-orange-50 text-orange-700",FINAL_QUOTED:"bg-violet-50 text-violet-700",USER_CONFIRMED:"bg-emerald-50 text-emerald-700",WAITING_PAYMENT:"bg-orange-50 text-orange-700",PAID:"bg-emerald-50 text-emerald-700",FULFILLING:"bg-blue-50 text-blue-700",BOOKED:"bg-emerald-50 text-emerald-700",COMPLETED:"bg-slate-100 text-slate-700",CANCELLED:"bg-slate-100 text-slate-600"};
export default async function MemberRequestsPage(){const userId=await requireUser("/member/requests");const items=await prisma.requirement.findMany({where:{userId},orderBy:{createdAt:"desc"},include:{quotes:{select:{id:true,price:true},take:1}},take:50});return <PlatformFrame title="我的需求" subtitle="跟踪顾问处理与报价进度" back="/member" active="member"><section className="px-5 py-6"><Link href="/inquiry" className="flex min-h-12 items-center justify-center gap-2 rounded-[17px] bg-[var(--app-blue)] text-[12px] font-semibold text-white"><Plus size={16}/>提交新的旅行需求</Link>{items.length?<div className="mt-5 space-y-3">{items.map(item=><Link key={item.id} href={`/member/requests/${item.id}`} className="app-card app-press block p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-[14px] font-semibold">{item.productName||item.destination||"旅行服务需求"}</p><p className="mt-2 line-clamp-2 whitespace-pre-line text-[10px] leading-5 text-[var(--app-muted)]">{item.content}</p>{item.estimatedMinPrice&&item.estimatedMaxPrice?<p className="mt-2 text-[10px] font-semibold text-blue-600">旅途预估 ¥{item.estimatedMinPrice.toLocaleString()}～¥{item.estimatedMaxPrice.toLocaleString()}{item.quotes[0]?` · 最终 ¥${item.quotes[0].price.toLocaleString()}`:""}</p>:null}</div><span className={`shrink-0 rounded-full px-2.5 py-1 text-[10px] font-semibold ${tones[item.status]||tones.SUBMITTED}`}>{labels[item.status]||item.status}</span></div><div className="mt-4 flex items-center justify-between border-t border-[#edf3f8] pt-3 text-[10px] text-[var(--app-muted)]"><span>{new Date(item.updatedAt).toLocaleDateString("zh-CN")}</span><span className="inline-flex items-center gap-1 text-[var(--app-blue)]">查看详情<ArrowRight size={12}/></span></div></Link>)}</div>:<div className="app-card mt-5 px-6 py-10 text-center"><ClipboardList size={27} className="mx-auto text-[var(--app-blue)]"/><h2 className="mt-3 text-[15px] font-semibold">还没有旅行需求</h2><p className="mt-2 text-[11px] leading-5 text-[var(--app-muted)]">先查看旅途预估，再提交给顾问确认实际可订方案。</p></div>}</section></PlatformFrame>}
