import Link from "next/link";
import { ClipboardList, Filter, Search } from "lucide-react";
import { AdminShell } from "@/components/hotel-admin/AdminShell";
import { requireAdmin } from "@/lib/adminAuth";
import { prisma } from "@/lib/prisma";
import { formatEstimateRange, formatYuan } from "@/lib/pricing/price-format";

const STATUS_LABELS: Record<string,string> = { SUBMITTED:"新需求",IN_REVIEW:"审核中",INQUIRING:"询价中",WAITING_FINAL_QUOTE:"待报价",FINAL_QUOTED:"已报价",USER_CONFIRMED:"用户已确认",WAITING_PAYMENT:"待付款",PAID:"已付款",FULFILLING:"履约中",BOOKED:"已成交",COMPLETED:"已完成",CANCELLED:"已取消" };
const FILTERS = [["","全部"],["SUBMITTED","新需求"],["INQUIRING","询价中"],["WAITING_FINAL_QUOTE","待报价"],["FINAL_QUOTED","已报价"],["USER_CONFIRMED","用户已确认"],["WAITING_PAYMENT","待付款"],["BOOKED","已成交"],["CANCELLED","已取消"]];

export default async function AdminRequirementsPage({searchParams}:{searchParams:Promise<{status?:string;q?:string}>}) {
  await requireAdmin("/admin/requirements");
  const {status,q}=await searchParams;
  const items=await prisma.requirement.findMany({where:{...(status?{status:status as never}:{}),...(q?{OR:[{requirementNo:{contains:q}},{productName:{contains:q}},{destination:{contains:q}},{contactPhone:{contains:q}}]}:{})},include:{user:{select:{nickname:true,mobile:true,email:true}},assignedStaff:{select:{realName:true,username:true}},quotes:{orderBy:{createdAt:"desc"},take:1}},orderBy:{createdAt:"desc"},take:100});
  return <AdminShell title="需求管理" subtitle="从预估意向到人工询价、最终报价与成交的统一工作台" headerExtra={<Link href="/admin/pricing" className="rounded-xl border border-[#dbe5f1] bg-white px-4 py-2 text-[12px] font-semibold text-[#0b4fd8]">价格规则与公开价格</Link>}><form className="flex flex-wrap gap-3 rounded-2xl border border-[#e5ebf3] bg-white p-4"><div className="relative min-w-[220px] flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input name="q" defaultValue={q||""} placeholder="需求编号、产品、目的地或手机号" className="h-11 w-full rounded-xl border border-slate-200 pl-10 pr-3 text-sm outline-none focus:border-blue-500"/></div><select name="status" defaultValue={status||""} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm">{FILTERS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#0b4fd8] px-5 text-sm font-semibold text-white"><Filter size={15}/>筛选</button></form><div className="mt-5 overflow-hidden rounded-2xl border border-[#e5ebf3] bg-white"><div className="hidden grid-cols-[1.1fr_1.3fr_.8fr_1fr_.8fr] gap-4 border-b border-slate-100 bg-slate-50 px-5 py-3 text-[11px] font-semibold text-slate-500 md:grid"><span>需求 / 用户</span><span>产品与价格</span><span>状态</span><span>提交时间</span><span>负责人</span></div>{items.map(item=><Link key={item.id} href={`/admin/requirements/${item.id}`} className="grid gap-3 border-b border-slate-100 px-5 py-4 transition last:border-0 hover:bg-blue-50/40 md:grid-cols-[1.1fr_1.3fr_.8fr_1fr_.8fr] md:items-center"><div><p className="text-[13px] font-semibold text-slate-900">{item.requirementNo||item.id.slice(-8).toUpperCase()}</p><p className="mt-1 text-[11px] text-slate-500">{item.user.nickname||item.user.mobile||item.user.email}</p></div><div><p className="text-[13px] font-medium text-slate-800">{item.productName||item.destination||`${item.type} 服务`}</p><p className="mt-1 text-[11px] text-slate-500">公开参考 {formatYuan(item.marketReferencePrice)} · 旅途预估 {formatEstimateRange(item.estimatedMinPrice,item.estimatedMaxPrice)}</p>{item.quotes[0]?<p className="mt-1 text-[11px] font-semibold text-blue-600">最终报价 {formatYuan(item.quotes[0].price)}</p>:null}</div><div><span className="inline-flex rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-semibold text-blue-700">{STATUS_LABELS[item.status]||item.status}</span></div><p className="text-[11px] text-slate-500">{new Date(item.createdAt).toLocaleString("zh-CN",{hour12:false})}</p><p className="text-[11px] text-slate-500">{item.assignedStaff?.realName||item.assignedStaff?.username||"待分配"}</p></Link>)}{!items.length?<div className="py-16 text-center"><ClipboardList size={28} className="mx-auto text-blue-500"/><p className="mt-3 text-sm text-slate-500">暂无符合条件的需求</p></div>:null}</div></AdminShell>;
}
