import Link from "next/link";
import { ArrowRight, BadgeCheck, Clock3, FileText } from "lucide-react";
import { PlatformFrame } from "@/components/platform/Catalog";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/userAuth";

const requirementLabels:Record<string,string>={SUBMITTED:"待处理",IN_REVIEW:"审核中",INQUIRING:"顾问确认中",WAITING_FINAL_QUOTE:"待最终报价",FINAL_QUOTED:"已报价",USER_CONFIRMED:"已确认",WAITING_PAYMENT:"待付款",PAID:"已付款",FULFILLING:"履约中",BOOKED:"已预订",COMPLETED:"已完成",CANCELLED:"已取消"};
const quoteLabels:Record<string,string>={DRAFT:"准备中",SENT:"待你确认",VIEWED:"待你确认",ACCEPTED:"已接受",EXPIRED:"已过期",REJECTED:"已拒绝"};
export default async function MemberQuotesPage(){const userId=await requireUser("/member/quotes");const items=await prisma.requirement.findMany({where:{userId},orderBy:{createdAt:"desc"},include:{quotes:{orderBy:{createdAt:"desc"}}}});return <PlatformFrame title="我的报价" subtitle="核对费用、包含项与确认状态" back="/member" active="member"><section className="px-5 py-6">{items.length?<div className="space-y-3">{items.map(item=>{const quote=item.quotes.find(q=>q.status==="SENT")||item.quotes[0];return <Link key={item.id} href={`/member/quotes/${item.id}`} className="app-card app-press block p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><p className="truncate text-[14px] font-semibold">{item.productName||"旅行服务需求"}</p><p className="mt-2 line-clamp-2 whitespace-pre-line text-[10px] leading-5 text-[var(--app-muted)]">{item.content}</p></div><div className="shrink-0 text-right">{quote?<><p className="text-[18px] font-semibold text-[var(--app-blue-deep)]">¥{quote.price.toLocaleString()}</p><span className="mt-1 inline-flex items-center gap-1 rounded-full bg-blue-50 px-2.5 py-1 text-[9px] font-semibold text-blue-700"><BadgeCheck size={11}/>{quoteLabels[quote.status]||quote.status}</span></>:<span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-2.5 py-1 text-[9px] font-semibold text-amber-700"><Clock3 size={11}/>{requirementLabels[item.status]||item.status}</span>}</div></div><div className="mt-4 flex items-center justify-between border-t border-[#edf3f8] pt-3 text-[10px] text-[var(--app-muted)]"><span>{new Date(item.createdAt).toLocaleDateString("zh-CN")}</span><span className="inline-flex items-center gap-1 text-[var(--app-blue)]">查看详情<ArrowRight size={12}/></span></div></Link>})}</div>:<div className="app-card px-6 py-12 text-center"><FileText size={28} className="mx-auto text-[var(--app-blue)]"/><h2 className="mt-3 text-[15px] font-semibold">还没有需求报价</h2><p className="mt-2 text-[11px] leading-5 text-[var(--app-muted)]">先提交酒店、旅行团或定制需求，顾问报价后会在这里更新。</p><Link href="/request" className="mt-5 inline-flex min-h-11 items-center rounded-[15px] bg-[var(--app-blue)] px-5 text-[12px] font-semibold text-white">提交需求</Link></div>}</section></PlatformFrame>}
