"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
export function NewSupplierForm() {
  const router = useRouter(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); const body = Object.fromEntries(form); const response = await fetch("/api/admin/suppliers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); setLoading(false); if (!response.ok) return setError(data.message || "创建失败"); router.push(`/admin/suppliers/${data.id}`); }
  return <form onSubmit={submit} className="max-w-2xl space-y-5 rounded-lg border border-[#dfe5ee] bg-white p-5"><div className="grid gap-4 sm:grid-cols-2"><Field name="brandName" label="对外品牌" required/><Field name="legalEntityName" label="法定名称" required/><Field name="slug" label="公开路径 slug" required/><label className="text-sm">供应商类型<select name="supplierType" className="mt-1 h-10 w-full rounded-lg border px-3"><option value="NATIONAL">全国性</option><option value="GBA_LOCAL">大湾区本地</option><option value="DESTINATION_DMC">目的地地接</option><option value="OVERSEAS_DMC">境外 DMC</option></select></label><Field name="province" label="省份/地区"/><Field name="city" label="城市"/><Field name="website" label="官方网站" type="url"/></div><label className="block text-sm">内部摘要<textarea name="summary" rows={4} className="mt-1 w-full rounded-lg border px-3 py-2"/></label>{error && <p className="text-sm text-red-700">{error}</p>}<p className="text-xs text-[#667085]">新建后默认为“刚发现”，不核验、不公开。</p><button disabled={loading} className="h-10 rounded-lg bg-[#1769e0] px-4 text-sm font-semibold text-white disabled:opacity-50">{loading ? "正在创建" : "创建候选机构"}</button></form>;
}
function Field({ name, label, required, type = "text" }: { name: string; label: string; required?: boolean; type?: string }) { return <label className="text-sm">{label}<input name={name} type={type} required={required} className="mt-1 h-10 w-full rounded-lg border px-3"/></label>; }

