"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, CheckCircle2, PhoneCall, ShieldCheck } from "lucide-react";
import { SUPPLIER_STATUSES } from "@/lib/supplierSchemas";

export function SupplierDetailActions({ id, currentStatus, isPublic, legalEntityName }: { id: string; currentStatus: string; isPublic: boolean; legalEntityName: string }) {
  const router = useRouter(); const [status, setStatus] = useState(currentStatus); const [reason, setReason] = useState(""); const [confirmed, setConfirmed] = useState(false); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function patch(body: Record<string, unknown>) { setBusy(true); setMessage(""); const response = await fetch(`/api/admin/suppliers/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); setBusy(false); if (!response.ok) return setMessage(data.message || "操作失败"); setMessage("已保存并写入审计日志"); router.refresh(); }
  return <div className="space-y-6">
    <section className="border-t border-[#dfe5ee] pt-5"><h2 className="text-base font-semibold">人工审核与状态</h2><div className="mt-3 grid gap-3 sm:grid-cols-[220px_1fr]"><select value={status} onChange={(e) => setStatus(e.target.value)} className="h-10 rounded-lg border px-3 text-sm">{SUPPLIER_STATUSES.map((value) => <option key={value} value={value}>{value}</option>)}</select><input value={reason} onChange={(e) => setReason(e.target.value)} placeholder="审核依据 / 状态变更原因" className="h-10 rounded-lg border px-3 text-sm"/></div><label className="mt-3 flex items-start gap-2 text-xs text-[#667085]"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} className="mt-0.5"/>我已核对主体、许可证和证据。VERIFIED / ACTIVE / 发布属于敏感操作。</label><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} onClick={() => patch({ status, reason, ...(confirmed ? { confirm: "CONFIRM" } : {}) })} className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#172033] px-4 text-sm font-semibold text-white disabled:opacity-50"><CheckCircle2 className="h-4 w-4"/>更新状态</button><button disabled={busy} onClick={() => patch({ isPublic: !isPublic, reason, ...(confirmed ? { confirm: "CONFIRM" } : {}) })} className="inline-flex h-10 items-center gap-2 rounded-lg border border-[#dfe5ee] bg-white px-4 text-sm font-semibold"><ShieldCheck className="h-4 w-4"/>{isPublic ? "取消发布" : "发布到前台"}</button></div>{message && <p className={`mt-3 text-sm ${message.startsWith("已") ? "text-emerald-700" : "text-red-700"}`}>{message}</p>}</section>
    <InteractionForm id={id}/><LicenseForm id={id} legalEntityName={legalEntityName}/>
  </div>;
}

function InteractionForm({ id }: { id: string }) { const router = useRouter(); const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); const contactedAt = new Date(String(values.contactedAt)).toISOString(); const followUpAt = values.followUpAt ? new Date(String(values.followUpAt)).toISOString() : null; const response = await fetch(`/api/admin/suppliers/${id}/interactions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, contactedAt, followUpAt }) }); const data = await response.json(); if (!response.ok) return setMessage(data.message || "保存失败"); form.reset(); setMessage("联系记录已保存"); router.refresh(); }
  return <section className="border-t border-[#dfe5ee] pt-5"><h2 className="flex items-center gap-2 text-base font-semibold"><PhoneCall className="h-4 w-4"/>添加联系记录</h2><form onSubmit={submit} className="mt-3 grid gap-3 sm:grid-cols-2"><input name="contactMethod" required placeholder="企业官方电话 / 合作表单" className="h-10 rounded-lg border px-3 text-sm"/><input name="contactedAt" required type="datetime-local" className="h-10 rounded-lg border px-3 text-sm"/><select name="channel" className="h-10 rounded-lg border px-3 text-sm"><option value="PHONE">电话</option><option value="EMAIL">邮件</option><option value="WECHAT_OFFICIAL">官方微信</option><option value="FORM">合作表单</option><option value="MEETING">会议</option><option value="OTHER">其他</option></select><input name="followUpAt" type="datetime-local" className="h-10 rounded-lg border px-3 text-sm"/><textarea name="outcome" required placeholder="沟通结果" rows={3} className="rounded-lg border px-3 py-2 text-sm sm:col-span-2"/><textarea name="nextStep" placeholder="下一步" rows={2} className="rounded-lg border px-3 py-2 text-sm sm:col-span-2"/><button className="h-10 rounded-lg bg-[#1769e0] px-4 text-sm font-semibold text-white sm:w-fit">保存联系记录</button>{message && <span className="self-center text-sm text-[#667085]">{message}</span>}</form></section>; }

function LicenseForm({ id, legalEntityName }: { id: string; legalEntityName: string }) { const router = useRouter(); const [message, setMessage] = useState(""); const [valid, setValid] = useState(false); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const body = Object.fromEntries(new FormData(form)); const response = await fetch(`/api/admin/suppliers/${id}/licenses`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...body, ...(valid ? { confirm: "CONFIRM" } : {}) }) }); const data = await response.json(); if (!response.ok) return setMessage(data.message || "保存失败"); form.reset(); setMessage("许可证已添加"); router.refresh(); }
  return <section className="border-t border-[#dfe5ee] pt-5"><h2 className="flex items-center gap-2 text-base font-semibold"><ShieldCheck className="h-4 w-4"/>补充许可证</h2><form onSubmit={submit} className="mt-3 grid gap-3 sm:grid-cols-2"><input name="licenseType" defaultValue="旅行社业务经营许可证" required className="h-10 rounded-lg border px-3 text-sm"/><input name="licenseNumber" required placeholder="许可证编号" className="h-10 rounded-lg border px-3 text-sm"/><input name="legalEntityName" defaultValue={legalEntityName} required className="h-10 rounded-lg border px-3 text-sm"/><input name="issuingAuthority" placeholder="发证机关" className="h-10 rounded-lg border px-3 text-sm"/><input name="evidenceUrl" required type="url" placeholder="https:// 官方核验链接" className="h-10 rounded-lg border px-3 text-sm"/><input name="validUntil" type="date" className="h-10 rounded-lg border px-3 text-sm"/><select name="status" onChange={(e) => setValid(e.target.value === "VALID")} className="h-10 rounded-lg border px-3 text-sm"><option value="UNVERIFIED">待核验</option><option value="VALID">有效（已人工核验）</option><option value="EXPIRED">过期</option><option value="CONFLICT">信息冲突</option><option value="NOT_FOUND">未找到</option></select><textarea name="businessScope" placeholder="许可经营范围" rows={2} className="rounded-lg border px-3 py-2 text-sm sm:col-span-2"/>{valid && <p className="flex items-start gap-2 text-xs text-amber-800 sm:col-span-2"><AlertTriangle className="h-4 w-4 shrink-0"/>提交即表示已从官方来源核对编号、主体、范围和有效期。</p>}<button className="h-10 rounded-lg border border-[#172033] px-4 text-sm font-semibold sm:w-fit">添加许可证</button>{message && <span className="self-center text-sm text-[#667085]">{message}</span>}</form></section>; }

