/* eslint-disable @next/next/no-html-link-for-pages */
import fs from "node:fs/promises";
import path from "node:path";
import Link from "next/link";
import { AlertTriangle, CheckCircle2, Download, FileJson } from "lucide-react";
import { AdminShell } from "@/components/hotel-admin/AdminShell";
import { requireAdmin } from "@/lib/adminAuth";
import { prisma } from "@/lib/prisma";
export default async function SupplierImportPage() { await requireAdmin("/admin/suppliers/import"); const file = path.join(process.cwd(), "research/suppliers/travel-agency-candidates.json"); const data = JSON.parse(await fs.readFile(file, "utf8")) as { researchDate: string; suppliers: Array<{ legalEntityName: string }> }; const legalNames = data.suppliers.map((x) => x.legalEntityName); const existing = await prisma.travelSupplier.count({ where: { legalEntityName: { in: legalNames } } }); return <AdminShell title="供应商导入预览" subtitle="默认 dry-run，导入前备份，冲突时整体回滚"><div className="max-w-3xl space-y-5"><div className="grid grid-cols-2 gap-px overflow-hidden rounded-lg border bg-[#dfe5ee] sm:grid-cols-4">{[["文件记录",data.suppliers.length],["准备新增",data.suppliers.length-existing],["已有主体",existing],["研究日期",data.researchDate]].map(([label,value]) => <div key={String(label)} className="bg-white p-4"><span className="text-xs text-[#667085]">{label}</span><strong className="mt-2 block text-xl">{value}</strong></div>)}</div><div className="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><div className="flex items-center gap-2 font-semibold"><CheckCircle2 className="h-4 w-4"/>当前导入结果</div><p className="mt-2 leading-6">{existing} 家候选已在本地数据库，全部保持 RESEARCHED、未核验、不公开。</p></div><div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><div className="flex items-center gap-2 font-semibold"><AlertTriangle className="h-4 w-4"/>正式导入仅通过受控 CLI</div><code className="mt-3 block overflow-x-auto rounded-md bg-white p-3 text-xs text-[#172033]">npm run suppliers:import -- --file research/suppliers/travel-agency-candidates.json --dry-run</code><code className="mt-2 block overflow-x-auto rounded-md bg-white p-3 text-xs text-[#172033]">npm run suppliers:import -- --file research/suppliers/travel-agency-candidates.json --commit</code></div><div className="flex flex-wrap gap-2"><Link href="/admin/suppliers" className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#1769e0] px-4 text-sm font-semibold text-white"><FileJson className="h-4 w-4"/>查看已导入候选</Link><a href="/api/admin/suppliers?pageSize=100" className="inline-flex h-10 items-center gap-2 rounded-lg border bg-white px-4 text-sm"><Download className="h-4 w-4"/>查看 JSON 接口</a></div></div></AdminShell>; }
