"use client";
import { useState } from "react";
import { CheckCircle2, Loader2 } from "lucide-react";

function Toggle({ checked, onChange }: { checked: boolean; onChange: (value: boolean) => void }) { return <button type="button" role="switch" aria-checked={checked} onClick={()=>onChange(!checked)} className={`relative h-7 w-12 rounded-full transition ${checked ? "bg-[var(--app-blue)]" : "bg-[#dbe3eb]"}`}><span className={`absolute top-1 size-5 rounded-full bg-white shadow transition ${checked ? "left-6" : "left-1"}`}/></button>; }

export function NotificationSettings({ initial }: { initial: { serviceNotifications: boolean; marketingNotifications: boolean } }) {
  const [serviceNotifications, setService] = useState(initial.serviceNotifications); const [marketingNotifications, setMarketing] = useState(initial.marketingNotifications); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  async function save() { setSaving(true); setSaved(false); setError(""); const response = await fetch("/api/preferences", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ serviceNotifications, marketingNotifications }) }); const json = await response.json().catch(()=>({})); setSaving(false); if (!response.ok) { setError(json.error || "保存失败"); return; } setSaved(true); }
  return <section className="px-5 py-6"><div className="app-card divide-y divide-[#edf3f8] px-4"><div className="flex min-h-[82px] items-center gap-4 py-4"><div className="flex-1"><p className="text-[13px] font-semibold">服务进度通知</p><p className="mt-1 text-[10px] leading-4 text-[var(--app-muted)]">报价、付款、订单与行程的重要状态</p></div><Toggle checked={serviceNotifications} onChange={setService}/></div><div className="flex min-h-[82px] items-center gap-4 py-4"><div className="flex-1"><p className="text-[13px] font-semibold">活动与灵感</p><p className="mt-1 text-[10px] leading-4 text-[var(--app-muted)]">目的地推荐、平台活动与旅行内容</p></div><Toggle checked={marketingNotifications} onChange={setMarketing}/></div></div><p className="mt-4 text-[10px] leading-5 text-[var(--app-muted)]">订单确认、退款、安全等必要服务通知可能无法完全关闭。</p>{error ? <p className="mt-4 rounded-[14px] bg-red-50 px-4 py-3 text-[11px] text-red-700">{error}</p> : null}{saved ? <p className="mt-4 flex items-center gap-2 rounded-[14px] bg-emerald-50 px-4 py-3 text-[11px] text-emerald-700"><CheckCircle2 size={15}/>设置已保存</p> : null}<button onClick={save} disabled={saving} className="mt-5 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-[17px] bg-[var(--app-blue)] text-[13px] font-semibold text-white">{saving ? <><Loader2 size={16} className="animate-spin"/>保存中…</> : "保存设置"}</button></section>;
}
