import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, CheckCircle2, Clock3, Headphones, ReceiptText } from "lucide-react";
import { PlatformFrame } from "@/components/platform/Catalog";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/userAuth";

const labels:Record<string,string>={SUBMITTED:"需求已提交",IN_REVIEW:"顾问审核中",INQUIRING:"顾问确认中",WAITING_FINAL_QUOTE:"等待最终报价",FINAL_QUOTED:"最终方案已确认",USER_CONFIRMED:"已确认预订",WAITING_PAYMENT:"等待付款",PAID:"已付款",FULFILLING:"正在履约",BOOKED:"预订已确认",COMPLETED:"服务已完成",CANCELLED:"已取消"};
export default async function MemberRequestDetailPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const userId=await requireUser(`/member/requests/${id}`);const item=await prisma.requirement.findFirst({where:{id,userId},include:{quotes:{orderBy:{createdAt:"desc"}}}});if(!item)notFound();const quote=item.quotes[0];return <PlatformFrame title="需求详情" subtitle={item.productName||"旅行服务需求"} back="/member/requests" active="member"><section className="px-5 py-6"><div className="rounded-[22px] bg-[#0d315d] p-5 text-white"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] text-white/60">当前进度</p><h1 className="mt-2 text-[22px] font-semibold">{quote?"顾问已提供报价":labels[item.status]||item.status}</h1><p className="mt-2 text-[11px] text-white/65">提交于 {new Date(item.createdAt).toLocaleString("zh-CN",{hour12:false})}</p></div>{quote?<CheckCircle2 size={27} className="text-[#8bd4ff]"/>:<Clock3 size={27} className="text-[#8bd4ff]"/>}</div></div><h2 className="mt-6 text-[16px] font-semibold">需求内容</h2><div className="app-card mt-3 p-4"><p className="whitespace-pre-line text-[12px] leading-6 text-[#53677e]">{item.content}</p>{item.contactName||item.contactPhone?<div className="mt-4 border-t border-[#edf3f8] pt-3 text-[10px] text-[var(--app-muted)]">联系人：{item.contactName||"-"} · {item.contactPhone||"-"}</div>:null}</div>{quote?<Link href={`/member/quotes/${item.id}`} className="mt-4 flex min-h-14 items-center gap-3 rounded-[18px] bg-[var(--app-blue)] px-4 text-white"><ReceiptText size={19}/><div className="flex-1"><p className="text-[12px] font-semibold">查看顾问报价</p><p className="mt-0.5 text-[10px] text-white/70">¥{quote.price.toLocaleString()} · 查看包含项与确认</p></div><ArrowRight size={16}/></Link>:<div className="mt-4 rounded-[18px] bg-[#fff8e8] p-4 text-[11px] leading-5 text-[#86693b]">顾问正在核对酒店、交通或相关旅行资源，报价完成后会在“我的报价”和通知中心同步更新。</div>}<Link href="/contact" className="mt-4 flex min-h-12 items-center justify-center gap-2 rounded-[16px] border border-[#dce8f4] bg-white text-[12px] font-semibold"><Headphones size={16}/>补充需求或联系顾问</Link></section></PlatformFrame>}
