import Link from "next/link";
import { CatalogHero, FilterChips, PlatformFrame, TourCard } from "@/components/platform/Catalog";
import { getPublicTours } from "@/lib/catalog/tours";

export default async function ToursPage({ searchParams }: { searchParams: Promise<{ filter?: string; q?: string }> }) {
  const [{ filter, q }, tours] = await Promise.all([searchParams, getPublicTours()]); const query = (q || "").trim();
  const list = tours.filter((t) => (!filter || filter === "全部" || t.type === filter || t.tags.includes(filter) || t.destination === filter) && (!query || `${t.name}${t.destination}${t.summary}`.includes(query)));
  const activeFilter = filter || "全部";
  return <PlatformFrame title="旅行团" subtitle="真实线路资料 · 感兴趣再问客服" active="discover"><CatalogHero eyebrow="TOUR COLLECTION" title="当前可咨询旅行团" note="现已整理川西与新疆线路资料；页面展示目的地、参考班期与参考价，最终名额和价格由客服确认。"/><FilterChips active={activeFilter} items={["全部", "精品小团", "自然风光", "川西秋色", "北疆秋色"]}/><form className="mx-5 mt-4 flex gap-2" method="get">{filter ? <input type="hidden" name="filter" value={filter} /> : null}<input name="q" defaultValue={query} placeholder="搜索目的地或产品名称" className="h-11 min-w-0 flex-1 rounded-[15px] border border-[#dce8f4] bg-white px-4 text-[13px] outline-none focus:border-[#1677ff]"/><button className="rounded-[15px] bg-[var(--app-blue)] px-5 text-[12px] font-semibold text-white">搜索</button></form><section className="mt-6 space-y-5 px-5"><div className="flex items-center justify-between"><p className="text-[12px] text-[var(--app-muted)]">共 {list.length} 条路线</p>{filter || query ? <Link href="/tours" className="text-[11px] font-semibold text-[var(--app-blue)]">清除筛选</Link> : null}</div>{list.map((tour)=><TourCard key={tour.slug} tour={tour}/>)}{!list.length&&<div className="app-card px-6 py-12 text-center"><p className="text-[16px] font-semibold">{tours.length ? "没有找到合适的旅行团" : "旅行团产品正在上新"}</p><p className="mt-2 text-[12px] leading-5 text-[var(--app-muted)]">{tours.length ? "换个目的地，或让客服按你的时间和预算匹配。" : "真实产品资料发布后会显示在这里，现在可先联系企业微信客服。"}</p><Link href="/contact" className="mt-5 inline-flex min-h-11 items-center rounded-full bg-[var(--app-blue)] px-5 text-[12px] font-semibold text-white">联系客服</Link></div>}</section></PlatformFrame>;
}
